#测试环境（test）
eureka:
  client:
    service-url:
      defaultZone: http://47.92.7.130:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: 47.92.7.130
    instance-id: ${eureka.instance.hostname}:${server.port}