#开发环境（dev）
eureka:
  client:
    service-url:
      defaultZone: http://134.175.54.165:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: 134.175.54.165
    instance-id: ${eureka.instance.hostname}:${server.port}