#本机环境（local）
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/