server:
  port: 8761

spring:
  application:
    name:  eureka-server
  profiles:
    active: prod
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.hostname}:${server.port}