server:
  port: 8761

spring:
  application:
    name:  eureka-server
  profiles:
    active: local

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}

---
#本机环境（local）
spring:
  profiles: local

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 6000
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

...

---
#开发环境（dev）
spring:
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.101:8761/eureka/,http://192.168.1.102:8761/eureka/,http://192.168.1.103:8761/eureka/

...

---
#测试环境（test）
spring:
  profiles: test

eureka:
  client:
    service-url:
      defaultZone: http://47.92.7.130:8761/eureka/

...

---
#生产环境（prod）
spring:
  profiles: prod

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.101:8761/eureka/,http://192.168.1.102:8761/eureka/,http://192.168.1.103:8761/eureka/

...