#本机环境（local）
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: 127.0.0.1
    instance-id: ${eureka.instance.hostname}:${server.port}