#生产环境（prod）
eureka:
  client:
    service-url:
      defaultZone: http://47.92.7.130:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instance-id: ${eureka.instance.hostname}:${server.port}