#生产环境（prod）
spring:
  rabbitmq:
    port: 5672
    addresses: 134.175.188.113
    username: guest
    password: guest
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/zyb23/config-repo/
          search-paths: yongyuanfeiyang
          username: zyb23
          password: 1qazcde35tgb
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://134.175.188.113:8761/eureka/