#本机环境（local）
spring:
  rabbitmq:
    port: 5672
    addresses: 127.0.0.1
    username: admin
    password: 123456

eureka:
  instance:
    lease-expiration-duration-in-seconds: 9
    lease-renewal-interval-in-seconds: 3
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"