#生产环境（prod）
spring:
  rabbitmq:
    port: 5672
    addresses: 192.168.1.101,192.168.1.102,192.168.1.103
    username: admin
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://47.92.7.130:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"