#测试环境（test）
spring:
  rabbitmq:
    port: 5672
    addresses: 47.92.7.130
    username: admin
    password: 123456
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zyb23/config-repo/
          search-paths: '{application}'
          username:
          password:
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://47.92.7.130:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: 47.92.7.130
    instance-id: ${eureka.instance.hostname}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"