#本机环境（local）
spring:
  rabbitmq:
    port: 5672
    addresses: 127.0.0.1
    username: admin
    password: 123456
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zyb23/config-repo/
          search-paths: '{application}'
          username: zyb23
          password: 1zhang2ying3bin.
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/