#开发环境（dev）
spring:
  rabbitmq:
    port: 5672
    addresses: 192.168.1.90
    username: guest
    password: guest
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/zyb23/config-repo/
          search-paths: '{application}'
          username: zyb23
          password: 1qazcde35tgb
          force-pull: true

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.90:8761/eureka/