#config-server取不到远程配置中心的配置，config-server启动后，加载远程配置中的配置文件到服务本地和内存，提供配置服务给config-client
server:
  port: 8888

logging:
  config: classpath:log4j2.yml

spring:
  application:
    name: config-server
  profiles:
    active: local
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/zyb23/config-repo/
          searchPaths:
          username: zyb23
          password: 1zhang2ying3bin.
          force-pull: true
    bus:
      enabled: true
      trace:
        enabled: true

eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}

---
#本机环境（local）
spring:
  profiles: local
  rabbitmq:
    port: 5672
    addresses: 127.0.0.1
    username: admin
    password: 123456

eureka:
  instance:
    lease-expiration-duration-in-seconds: 9
    lease-renewal-interval-in-seconds: 3
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

...

---
#开发环境（dev）
spring:
  profiles: dev
  rabbitmq:
    port: 5672
    addresses: 192.168.1.101,192.168.1.102,192.168.1.103
    username: admin
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.101:8761/eureka/,http://192.168.1.102:8761/eureka/,http://192.168.1.103:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

...

---
#测试环境（test）
spring:
  profiles: test
  rabbitmq:
    port: 5672
    addresses: 47.92.7.130
    username: admin
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://47.92.7.130:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

...

---
#生产环境（prod）
spring:
  profiles: prod
  rabbitmq:
    port: 5672
    addresses: 192.168.1.101,192.168.1.102,192.168.1.103
    username: admin
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.101:8761/eureka/,http://192.168.1.102:8761/eureka/,http://192.168.1.103:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

...