#测试环境（test）
spring:
  rabbitmq:
    port: 5672
    addresses: 47.92.7.130
    username: admin
    password: 123456

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.101:8761/eureka/,http://192.168.1.102:8761/eureka/,http://192.168.1.103:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"